// User reducer types
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const SET_USER_DETAILS = "SET_USER_DETAILS";
export const CLEAR_ERRORS_USER = "CLEAR_ERRORS_USER";
export const SET_ERRORS_USER = "SET_ERRORS_USER";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOADING_USER = "LOADING_USER";

// **AUTH**
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
// **SIGN UP**
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
// **SIGN IN**
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";
// **SIGN OUT**
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_ERROR = "SIGNOUT_ERROR";
// **RESET PASSWORD**
export const RESET_SUCCESS = "RESET_SUCCESS";
export const RESET_ERROR = "RESET_ERROR";
